# Generated by Django 5.1.1 on 2024-10-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invista_me', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investimento',
            old_name='Investimento',
            new_name='investimento',
        ),
    ]
